import { Inter } from 'next/font/google'
import './globals.css'
import NavBarMenu from './components/NavBar'
import Footer from './components/Footer'
import { Outfit } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const outfit = Outfit({
  subsets:['latin'],
  weight: ['300', '200'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <NavBarMenu />  
        {children}
        <Footer />
        </div>
        
        </body>
    </html>
  )
}
