import './globals.css'
import NavBarMenu from './components/NavBar'
import Footer from './components/Footer'
import { Outfit, Italiana } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

const italiana = Italiana({
  subsets:['latin'],
  weight:  '400',
  variable: '--font-italiana',
})

const outfit = Outfit({
  subsets:['latin'],
  weight: '200',
  variable: '--font-outfit',
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${italiana.variable} ${outfit.variable} `} >
      <body className={outfit.className} >
        <NavBarMenu />  
        {children}
        <Footer />
        </body>
    </html>
  )
}
